# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: swift
# cache: cocoapods
# podfile: Example/Podfile
rvm:
  - 2.2.2

before_install:
  - gem install cocoapods --version 1.1.0.rc2

script:
- set -o pipefail && xcodebuild test -workspace Example/StringCase.xcworkspace -scheme StringCase-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
